parameters:
    open_orchestra_elastica.schema_initializer.content_type.class: OpenOrchestra\Elastica\SchemaInitializer\Strategies\ContentTypeSchemaInitializer
    open_orchestra_elastica.schema_initializer.manager.class: OpenOrchestra\Elastica\SchemaInitializer\SchemaInitializerManager

services:
    open_orchestra_elastica.schema_initializer.manager:
        class: %open_orchestra_elastica.schema_initializer.manager.class%

    open_orchestra_elastica.schema_initializer.content_type:
        class: %open_orchestra_elastica.schema_initializer.content_type.class%
        arguments:
            - @open_orchestra_model.repository.content_type
            - @open_orchestra_elastica.schema_generator.content_type
        tags:
            - { name: open_orchestra_elastica.schema_initializer.strategy }