parameters:
    open_orchestra_elastica.subscriber.content_index.class: OpenOrchestra\Elastica\EventSubscriber\UpdateContentIndexedSubscriber
    open_orchestra_elastica.subscriber.node_index.class: OpenOrchestra\Elastica\EventSubscriber\UpdateNodeIndexedSubscriber
    open_orchestra_elastica.subscriber.content_schema.class: OpenOrchestra\Elastica\EventSubscriber\UpdateContentSchemaSubscriber

services:
    open_orchestra_elastica.subscriber.content_index:
        class: '%open_orchestra_elastica.subscriber.content_index.class%'
        arguments:
            - '@open_orchestra_model.repository.content'
            - '@open_orchestra_elastica.indexor.content'
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_elastica.subscriber.content_schema:
        class: '%open_orchestra_elastica.subscriber.content_schema.class%'
        arguments:
            - '@open_orchestra_elastica.schema_generator.content_type'
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_elastica.subscriber.node_index:
        class: '%open_orchestra_elastica.subscriber.node_index.class%'
        arguments:
            - '@open_orchestra_model.repository.node'
            - '@open_orchestra_elastica.indexor.node'
        tags:
            - { name: kernel.event_subscriber }
