parameters:
    open_orchestra_elastica.transformer.content.class: OpenOrchestra\Elastica\Transformer\ContentTransformer
    open_orchestra_elastica.transformer.node.class: OpenOrchestra\Elastica\Transformer\NodeTransformer

services:
    open_orchestra_elastica.transformer.content:
        class: '%open_orchestra_elastica.transformer.content.class%'
    open_orchestra_elastica.transformer.node:
        class: '%open_orchestra_elastica.transformer.node.class%'
        arguments:
            - '@open_orchestra_backoffice.display_block_manager'
